### ISSUE TITLE
Why was the subdomain code removed

### ISSUE THREAD

**Issue by sebakerckhof** [flipace/meteor-tenantify#2]
Hey,

I'm looking to implement subdomain based multi-tenancy in my meteor project.
I saw this project had this before, but it has been removed.
I was just wondering what was the reason for the removal? Maybe I could learn from it and avoid running in the same problems you did.

Thanks

**Comment by flipace** [comment]
It's been quiet some time since i removed it but here's a few things i still remember:
- it was hard to do stuff like a management dashboard which can oversee data of multiple tenants (could've been implemented in a separate app or additional code)
- i didn't like that the subdomain logic was tied to this package since you might want to change the logic which decides which tenant to use to something else entirely but still use a little helper package which allows you to easily filter results

So it's not been anything unsolvable, i'd just recommend to look out for how you might want to access data in the future, so you don't look yourself into some setup which doesn't allow you to to user-impersonation or something like that :)

**Comment by sebakerckhof** [comment]
K, thanks for that info.
